jQuery.sap.registerPreloadedModules({
"version":"2.0",
"modules":{
	"com/sapyard/covid19/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","com/sapyard/covid19/model/models","sap/ui/model/json/JSONModel"],function(e,i,t,o){"use strict";return e.extend("com.sapyard.covid19.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(t.createDeviceModel(),"device")}})});
},
	"com/sapyard/covid19/controller/App.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/model/json/JSONModel"],function(e,t){"use strict";return e.extend("com.sapyard.covid19.controller.App",{onInit:function(){this.covidModel=new t({data:[],selectedData:{}});this.covidModel.setSizeLimit(1500);this.getView().setModel(this.covidModel);this.getCovidAllCountryData()},getCovidAllCountryData:function(){this.covidModel.setProperty("/data",[]);$.ajax({url:"https://coronavirus-19-api.herokuapp.com/countries",success:this.onCovidDataSuccess.bind(this),error:this.onCovidDataFail.bind(this)})},onCovidDataSuccess:function(e){debugger;this.covidModel.setProperty("/data",e);this.getCovidOverview()},onCovidDataFail:function(e){},getCovidOverview:function(){$.ajax({url:"https://coronavirus-19-api.herokuapp.com/all",success:this.ongetCovidOverviewSuccess.bind(this),error:this.ongetCovidOverviewFail.bind(this)})},ongetCovidOverviewSuccess:function(e){this.global=e;this.global.country="Global";this.global.text=this.global.country;this.covidModel.getProperty("/data").push(this.global);this.covidModel.refresh(true);this.setDefault()},ongetCovidOverviewFail:function(e){},setDefault:function(){var e=this.getView().byId("overviewId");var t=e.getSelectedKey();if(t){}else{e.setSelectedKey("Global")}debugger;e.fireSelectionChange()},onCountrySelect:function(e){debugger;var t=e.getSource().getSelectedItem();if(t){this.covidModel.setProperty("/selectedData",t.getBindingContext().getObject())}}})});
},
	"com/sapyard/covid19/i18n/i18n.properties":'title=Title\nappTitle=covid19\nappDescription=App Description\ncovidTitle = Covid-19\nconfirmed=Confirmed\nrecovered=Recovered\ndeaths=Deaths',
	"com/sapyard/covid19/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"com.sapyard.covid19","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}","sourceTemplate":{"id":"ui5template.basicSAPUI5ApplicationProject","version":"1.40.12"}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":false,"rootView":{"viewName":"com.sapyard.covid19.view.App","type":"XML","async":true,"id":"App"},"dependencies":{"minUI5Version":"1.65.6","libs":{"sap.ui.layout":{},"sap.ui.core":{},"sap.m":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"com.sapyard.covid19.i18n.i18n"}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"com.sapyard.covid19.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"RouteApp","pattern":"RouteApp","target":["TargetApp"]}],"targets":{"TargetApp":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"App","viewName":"App"}}}}}',
	"com/sapyard/covid19/model/delet_countrylist.json":'{"CountriesCollection":[{"key":"DZ","text":"Algeria"},{"key":"AR","text":"Argentina"},{"key":"AU","text":"Australia"},{"key":"AT","text":"Austria"},{"key":"BH","text":"Bahrain"},{"key":"BE","text":"Belgium"},{"key":"BA","text":"Bosnia and Herzegovina"},{"key":"BR","text":"Brazil"},{"key":"BG","text":"Bulgaria"},{"key":"CA","text":"Canada"},{"key":"CL","text":"Chile"},{"key":"CO","text":"Colombia"},{"key":"HR","text":"Croatia"},{"key":"CU","text":"Cuba"},{"key":"CZ","text":"Czech Republic"},{"key":"DK","text":"Denmark"},{"key":"EG","text":"Egypt"},{"key":"EE","text":"Estonia"},{"key":"FI","text":"Finland"},{"key":"FR","text":"France"},{"key":"GER","text":"Germany"},{"key":"GH","text":"Ghana"},{"key":"GR","text":"Greece"},{"key":"HU","text":"Hungary"},{"key":"IN","text":"India"},{"key":"ID","text":"Indonesia"},{"key":"IE","text":"Ireland"},{"key":"IL","text":"Israel"},{"key":"IT","text":"Italy"},{"key":"JP","text":"Japan"},{"key":"JO","text":"Jordan"},{"key":"KE","text":"Kenya"},{"key":"KW","text":"Kuwait"},{"key":"LV","text":"Latvia"},{"key":"LT","text":"Lithuania"},{"key":"MK","text":"Macedonia"},{"key":"MY","text":"Malaysia"},{"key":"MX","text":"Mexico"},{"key":"ME","text":"Montenegro"},{"key":"MA","text":"Morocco"},{"key":"NL","text":"Netherlands"},{"key":"NZ","text":"New Zealand"},{"key":"NG","text":"Nigeria"},{"key":"NO","text":"Norway"},{"key":"OM","text":"Oman"},{"key":"PE","text":"Peru"},{"key":"PH","text":"Philippines"},{"key":"PL","text":"Poland"},{"key":"PT","text":"Portugal"},{"key":"QA","text":"Qatar"},{"key":"RO","text":"Romania"},{"key":"RU","text":"Russia"},{"key":"SA","text":"Saudi Arabia"},{"key":"SN","text":"Senegal"},{"key":"RS","text":"Serbia"},{"key":"SG","text":"Singapore"},{"key":"SK","text":"Slovakia"},{"key":"SI","text":"Slovenia"},{"key":"ZA","text":"South Africa"},{"key":"KR","text":"South Korea"},{"key":"ES","text":"Spain"},{"key":"SE","text":"Sweden"},{"key":"CH","text":"Switzerland"},{"key":"TN","text":"Tunisia"},{"key":"TR","text":"Turkey"},{"key":"UG","text":"Uganda"},{"key":"UA","text":"Ukraine"},{"key":"AE","text":"United Arab Emirates"},{"key":"GB","text":"United Kingdom"},{"key":"YE","text":"Yemen"}]}',
	"com/sapyard/covid19/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"com/sapyard/covid19/view/App.view.xml":'<mvc:View controllerName="com.sapyard.covid19.controller.App" xmlns:mvc="sap.ui.core.mvc" displayBlock="true" xmlns="sap.m"\n\txmlns:l="sap.ui.layout" xmlns:core="sap.ui.core"><Shell id="shell"><App id="appId"><pages><Page id="page" title="{i18n>covidTitle}"><content><Panel class="sapUiDemoFlexBoxSizeAdjustments"><FlexBox alignItems="Start"><items><l:VerticalLayout><Text text="Overview"></Text><ComboBox id="overviewId" selectionChange="onCountrySelect"\n\t\t\t\t\t\t\t\t\t\t\titems="{/data}" ><core:ListItem key="{country}" text="{country}"/></ComboBox><l:layoutData><FlexItemData growFactor="1"/></l:layoutData></l:VerticalLayout><l:VerticalLayout><Title titleStyle="H1" text="{/selectedData/cases}"></Title><Text text="{i18n>confirmed}"></Text><l:layoutData><FlexItemData growFactor="1"/></l:layoutData></l:VerticalLayout><l:VerticalLayout><Title titleStyle="H1" text="{/selectedData/recovered}"></Title><Text text="{i18n>recovered}"></Text><l:layoutData><FlexItemData growFactor="1"/></l:layoutData></l:VerticalLayout><l:VerticalLayout><Title titleStyle="H1" text="{/selectedData/deaths}"></Title><Text text="{i18n>deaths}"></Text><l:layoutData><FlexItemData growFactor="1"/></l:layoutData></l:VerticalLayout></items></FlexBox></Panel></content></Page></pages></App></Shell></mvc:View>'
}});
